name:                hacc
version:             0.1.0.0
license:             BSD3
author:              "Lovro Lugović"
maintainer:          "lugovic@imada.sdu.dk"
copyright:           "2023 Lovro Lugović"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Compositional Choreographies to Jolie Compiler
# category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- containers
- deepseq
- spoon

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hacc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hacc

tests:
  hacc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hacc
